version: "1"
services:
  web:
    image: centos:7
    ports:
      - "5000:80"

  #   command: ['/usr/bin/dumb-init', '/usr/sbin/apache2ctl', '-D', 'FOREGROUND']
  #   dev_overrides:
  #     environment:
  #       - "DEBUG=1"
  #
registries: {}
