---
- name: Deploy Flask App
  hosts: atomic
  become: yes

  vars:
    src_dir: /var/lib/jenkins/workspace/git-annsible/examples/flask-helloworld       # /path/to/src_dir of the current host.
    dest_dir: /var/lib/jenkins/workspace  # /path/to/dest_dir of the remote atomic host.

  tasks:
    - name: Create Destination Directory
      file:
       path: "{{ dest_dir }}/source"
       state: directory
       recurse: yes

    - name: Copy Dockerfile to host
      copy:
       src: "{{ src_dir }}/Dockerfile"
       dest: "{{ dest_dir }}"

    - name: Copy Application to host
      copy:
       src: "{{ src_dir }}/flask-helloworld/"
       dest: "{{ dest_dir }}/source/"

    - name: Make sure that the current directory is {{ dest_dir }}
      command: cd {{ dest_dir }}

    - name: Build Docker Image
      command: docker build --rm -t fedora/flask-app:test -f "{{ dest_dir }}/Dockerfile" "{{ dest_dir }}"

    - name: Run Docker Container
      command: docker run -d --name helloworld -p 5000:5000 fedora/flask-app:test

    - name: Start Cockpit Service
      command: /usr/bin/atomic run fedora/cockpitws
...
