---
- name: Redis server
  hosts: atomic
  become: yes
  tasks:
    - name: Run Redis container
      docker_container:
        name: myredis
        image: fedora/redis
        ports: 6379:6379
        state: started
        detach: yes
...
